# Gradle properties
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
# Android
android.useAndroidX=true
android.nonTransitiveR8=true
android.experimental.r8.dex-startup-optimization=true
android.suppressUnsupportedCompileSdk=35,36
# Kotlin
kotlin.code.style=official
kotlin.incremental=true
# Compose
android.compose.reporter.enabled=true
